#!/bin/bash

# Custom Rofi Script

# Launch Rofi
MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p '' \
-hide-scrollbar true \
-bw 0 \
-lines 1 \
-line-padding 10 \
-theme-str 'prompt { enabled: false; }' \
-fixed-num-lines true \
-columns 5 \
-icon-theme "Papirus" \
<<< "||勒|襤")"
case "$MENU" in
  ) dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock ;;
  ) gnome-session-quit --logout ;;
  勒)  gnome-session-quit --reboot ;;
  襤) gnome-session-quit --power-off

esac

# More Options
# -fullscreen \
